const quotes = {
  "1": "I just want everyone to be awesome. That’s all it is. I want everyone to be cool in their own way.",
  "2": "I’m an optimistic guy. I’m one of those big dreamers. I’m one of those kids with that annoying imagination.",
  "3": "Being in love is cool as hell, like having feelings and sh*t, it’s tight.",
  "4": "If the world was ending, I think I would grab some Cinnamon Toast Crunch, a bunch of water, and I’d probably just… I’d probably go crazy.",
  "5": "I never had a drink in my life. I don’t smoke or anything.",
  "6": "I was sitting like, there’s nothing I want to buy. I was fully okay with life. It was nothing I was stressed about. I wasn’t sore nowhere. I’m financially good. Everyone around me is healthy. No grudges. The weather was great.",
  "7": "Honestly, I’m a weak bitch. My punches are not good. I can run fast, but if I had to hold somebody from falling off a cliff, they’re going to die.",
  "8": "I’m f**king stoked. My life is sick. I get to still skate around like I did three years ago. I might have to take a couple of pictures, but whatever. I have money to go do stupid sh*t. I couldn’t ask for nothing else.",
  "9": "Do what the f**k makes you happy. Because in the end, who’s there? You. ― Tyler, the Creator",
  "10": "Don’t be scared of color.",
  "11": "Do something productive, stay the f**k off of Snapchat.",
  "12": "It’s actually beautiful that we’re aware of this superpower that we have where we’re just us, no matter what. We don’t get nervous in front of people. We look in the mirror and we’re okay with it.",
  "13": "People are more obsessed with the idea of failing than the idea of succeeding.",
  "14": "I think people get caught up in having an identity.",
  "15": "Wherever my curiosity takes me, I follow. If I f**king hate it, I’m on to the next thing. A lot of people don’t move like that and it just boggles my mind. It’s like a math problem I can’t comprehend.",
  "16": "You gotta keep things fun…Laughing is really important to your health, believe it or not, so I guess I just always try to have fun and keep the energy alive.",
  "17": "My lyrics aren’t offensive. Some people find everything offensive.",
  "18": "I’m like a big 10-year-old when I’m on stage. I just go up there and do whatever I think is cool at the time.",
  "19": "I want to take Justin Bieber for a month and just lock him up in a cage where we sit and make music. He’s one of the most successful people in the world, but his music could be so much tighter.",
  "20": "I’m not hip-hop. I’m Tyler.",
  "21": "I don’t have a therapist, so I use me as my own therapist when I’m making the music.",
  "22": "Usually, when I’m rappin’, I’m creating a big story or a concept song that sounds like a movie to me.",
  "23": "Long story short, my biggest songs to date are all singing songs. And the people who were saying that I was bad were just projecting their inner fears of trying something that they wanted to try, but not being able to. And now I’m better at singing and they’re probably not better at whatever they wanted to do.",
  "24": "I want to design jewelry for girls and guys… I’ma spread it out, but I’ma design, probably when I’m just designing furniture and buildings, I’ll probably being the jewelry thing, too.",
  "25": "Rap is really just too conventional. Everybody does the same thing. No one ever pushes the box.",
  "26": "Ni**a be like why didn’t my fav rapper blow up prolly cause he has the personality of a chair ni**as be flat haha.",
  "27": "Since day one, I’ve always wanted to make the prettiest s*it that’s borderline boring or the hardest f**king sh*t…I’ve been trying to mix those together since my first album.",
  "28": "I love talking about music. I’ll show you a song and break it down for 50 minutes. I’m a geek about it.",
  "29": "There are people I really admire. But they influence me pretty heavy right now because my own style is still blossoming. So I’m not going to tell you who they are because then you’ll know where I’m stealing from.",
  "30": "I want to do films and have my name mentioned next to Wes Anderson and Quentin Tarantino. I don’t want my name mentioned next to other rappers at all.",
  "31": "I wasn’t shy, but I was really hyper. Nobody got my sense of humor. I was a black skater kid.",
  "32": "I want to make as much money as I possibly can so that when my day comes, my mother and sister is fine. My close friends are fine. They don’t have to worry about anything ever again.",
  "33": "I just live life. I grew up in a Christian family, but, you know, the way Mom brought me up is to, you know, do you, to always be yourself.",
  "34": "Hawthorne sucks… It’s a crazy place, and I’m happy that I was the weird one that got out.",
  "35": "I think, if I had a dad, I would have went the normal college route. I’m so stoked my life panned out how it was.",
  "36": "I’m a big ‘Goosebumps’ fan – ‘Revenge of the Lawn Gnomes.’ My favorites are the pick-your-own-death ones.",
  "37": "Humans have voids, and you need things to fill voids… I didn’t have a dad to fill that male model void, so when I heard Eminem or freaking seen Dave Chapelle, that’s what I gravitated to.",
  "38": "I was just such an erratic, wild personality….When you finally find someone to listen to you after years of not being taken seriously, you hold that sh*t to your heart.",
  "39": "Tell these black kids they can be who they are. Dye your hair blue. Sh*t, I’ll do it too.",
  "40": "In school I was the one thinking outside of boxes, so everybody in them would say I got problems.",
  "41": "They say success is the best revenge so I beat DeShay up with the stack of magazines I’m in.",
  "42": "I’m the loneliest man alive, but I keep on dancing to throw ’em off.",
  "43": "You make my earth quake.",
  "44": "I can grab the fireworks, the soda, all the cookies we can eat. Make you nauseous but be cautious, this is not Dawson’s Creek.",
  "45": "Listen deeper than the music before you put it in the box.",
  "46": "I’m not into fashion, but I like design. I wear the same shoes every day.",
  "47": "For the record, I don’t worship the devil. I just hate religion.",
  "48": "I don’t like people around me sad. I like making people happy.",
  "49": "I think I’m cool. That’s all that matters.",
  "50": "I don’t really listen to rap; I just like to rap.",
  "51": "I really want to sing, but my tone of voice is really too deep to do what I want.",
  "52": "I like my raps, but I’m never too happy with some of ’em because I feel like they could be better.",
  "53": "The thing is, I make music I like. So it’s just weird if someone says they don’t like it.",
  "54": "I’m hungry for VMAs and Grammys. That’s my main goal.",
  "55": "Hahahahahahahaha How The Fuck Is Cyber Bullying Real Hahahaha Nigga Just Walk Away From The Screen Like Nigga Close Your Eyes Haha",
  "56": "I CRIED WHEN THEY KILLED BENNY IN CITY OF GOD. I WAS ANGRY FOR A FUCKING WEEK. THAT WAS FUCKED UP. REAL FUCKED UP."
}


  module.exports = {
    quotes
  }

